name: interlakesdrops
favicon: null
layout_spectrum: 0.5346506484784186
typography_spectrum: 0.465116890380159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9789139681961387
  lightness: 0.7951134729664773
  saturation: 0.22625253978185356
  rhythmicContrast: 0.34296536864712834
purpose: []
